import localFont from "next/font/local";
import "@/globals.css";
import AuthNav from "../component/authNav"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className='styled-background'
      >
        <AuthNav />
        {children}
      </body>
    </html>
  );
}
